### ISSUE TITLE
Updates.

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabD-Team1#1]
Need comments and possible new ideas. I was thinking of possible other shapes, animation options, and color.

**Comment by alternatebow** [comment]
Possibly one that randomly generates a different color for each shape?

**Comment by karlnicholas** [comment]
I like it. Possibly add a drop-down menu with "special effects" entries?

**Comment by alternatebow** [comment]
Yeah that would be pretty cool. What kind of special effects are we talking
about here?

**Comment by karlnicholas** [comment]
Well, whatever we put in there. a "Random Colors" entry. Maybe mixed shapes?

**Comment by alternatebow** [comment]
Yo... I took a look at the project... Dude... your programming skills are ridiculously good. What you made is beyond anything that I had in mind for this lab to begin with. I'm just pointing that out. Not really sure what I can add to this...

**Comment by karlnicholas** [comment]
Random colors! ;)

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Oct 1, 2016 at 4:46 PM -0700, "alternatebow" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yo... I took a look at the project... Dude... your programming skills are ridiculously good. What you made is beyond anything that I had in mind for this lab to begin with. I'm just pointing that out. Not really sure what I can add to this...

-

**Comment by ggorlen** [comment]
Whoa, nice project!!

**Comment by karlnicholas** [comment]
Thanks Calvin and Greg!

Calvin, I encourage you to look some more. From a code point of view having the recurse routine in a class separate from the polygon made me feel uncomfortable, so that can probably be refactored. Adding comments is always a good way to get more familiar with the code. Also, the shape uses a polygon, but it's setup to use anything you want. For example, why do we have to have straight lines between the verticies of the polygon? Why not connect them with circles? Why does it have to be filled solid? You can re-implement the GraphicsShape interface and just change the drawing commands a little bit and you should get some interesting results. 

At some point you need to think beyond the coding problems and think about the problem itself. If you really want to get fancy you can implement a GraphicsShape that doesn't depend on the built in drawing commands like it currently does. You can draw a T or a Start or a Hash or use images (cats are always popular) 

Even something like a color chooser would be an improvement. You can add another button panel on the Top move the animate button there and put a simple RED, GREEN, BLUE color chooser in it's place. Then you'll have to propagate that choice around. If you where a first hire, it wouldn't be unreasonable to expect to be given a program much more complex than this be told to "add a color chooser functionality" Deadline next Monday and you're late! 👍 

@jillHuang7 Jill, you're still around. This is a good chance to get some tech-writer skills and comment the code and perhaps document it as well as thinking about new functionality. Remember, a project takes all kinds to be successful.

**Comment by karlnicholas** [comment]
Alright, color looks pretty good, but there is a System.out for Color in there somewhere. See if you can find that and remove it. Tx.

**Comment by karlnicholas** [comment]
sweet

**Comment by karlnicholas** [comment]
For additions I suggest 1) adding new shapes. It should be a lot easier now that there are two already in there. 2) I'm still interested in the color ideas, especially if it happens during animation b/c that would look totally cool.

Also, during animation I wanted to change the radius and rotation to go to 180 instead of 150 b/c 180 is a half circle. That can be done anytime.

Let me know what you are thinking and doing be sure to communicate so that you aren't working on the same thing as someone else.

**Comment by alternatebow** [comment]
That sounds good. I'm working on the color change shift right now (based on
radius)

**Comment by alternatebow** [comment]
Exception in thread "AWT-EventQueue-1" java.lang.NoClassDefFoundError: GraphicsCircles
	at RecursionProgram.addComponentsToPane(RecursionProgram.java:142)
	at RecursionProgram.createAndShowGUI(RecursionProgram.java:161)

I keep getting this issue even though I see the GraphicsCircles class. Not sure why it keeps saying it's undefined

**Comment by karlnicholas** [comment]
Not seeing it. Delete all the .class files and rebuild. Otherwise perhaps we can google hangout.

**Comment by karlnicholas** [comment]
done.
