### ISSUE TITLE
the minimum length of a size of a square

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabD-Team1#21]
A requirement: the **minimum** length of a size of a square as an instance variable.

In all this fun, we have set "radius" > 10" in the recursion routine, but it needs to be an "instance variable" , so we need to add that.

**Comment by karlnicholas** [comment]
I'll get this tomorrow.

**Comment by jillHuang7** [comment]
I am thinking to declare this in GraphicsPolygon class:

public static final int SquareRadius = 10;

but it looks like ShapeContainer needs to set a constant for square radius too...
any thoughts? Or need to put this constant in both class?

**Comment by karlnicholas** [comment]
Hi Jill, 
I was thinking it needs to be another parameter like "sides" or "radius". This would be set in ShapeContainer and passed as part of the constructor for all of the Shapes. Sorry I didn't get to it yesterday but if you're willing do to it that's fine with me.

**Comment by alternatebow** [comment]
That's just the minimal radius correct?

**Comment by karlnicholas** [comment]
oh, yea. Anyway, how about a dropdown for minimum radius with values 10,20,40,80, & 160. That should work out ok.

**Comment by karlnicholas** [comment]
Last issue, I think Jill wanted to tackle this one.

**Comment by karlnicholas** [comment]
Jill, I see you have a branch, but you need to make a pull request for it.

**Comment by jillHuang7** [comment]
Yup, sorry that I forgot to do that.

**Comment by jillHuang7** [comment]
Oops, looks I checked too late?!

**Comment by karlnicholas** [comment]
Got it merged.

**Comment by karlnicholas** [comment]
I'll finish it up. Thanks for your efforts.

**Comment by karlnicholas** [comment]
Looks good.
