### ISSUE TITLE
Create Zip file and Submit

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabD-Team1#25]
Create Zip file and Submit all Java files.

**Comment by karlnicholas** [comment]
From:                              Do not reply to this email <noreply@rl01-v1082.rlem.net>
Sent:                               Sunday, October 9, 2016 3:03 PM
To:                                   Karl Nicholas
Subject:                          You have submitted your assignment submission for Lab D: Recursion
 
CS111C-META-FALL-2016 ->Assignment ->Lab D: Recursion

You have submitted an assignment submission for 'Lab D: Recursion'.
You can see the status of your [assignment submission](https://insight.ccsf.edu/mod/assign/view.php?id=557968).

**Comment by ggorlen** [comment]
can't wait to re-download this masterpiece!
