### ISSUE TITLE
Make an executable jar file.

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabD-Team1#28]
Hey guys, I think the instructor likes it ...

> Group: Karl Nicholas, Calvin Lee, and Yu-Hsiang Huang
> excellent job! you should make this an executable jar and share it- it's an awesome program! i love the animation! very nice work.
> +15 extra credit

**Comment by jillHuang7** [comment]
I just saw. You did a great program, Karl! Calvin provided a lot too! I am
learning form you guys😖.

**Comment by karlnicholas** [comment]
Making an executable file is pretty straight forward. If we can make it then I'd appreciate it if you would post on insight with simple instructions and a link.

**Comment by jillHuang7** [comment]
Ok. Let me try on this.

**Comment by alternatebow** [comment]
Lol yeah I noticed that. Pleasure working with y'all.

**Comment by karlnicholas** [comment]
Calvin, are you able to help with putting together an executable jar file? I think this link helps:

[How to make an executable jar file?](http://stackoverflow.com/questions/5258159/how-to-make-an-executable-jar-file)

**Comment by alternatebow** [comment]
Um sure. I'll help

**Comment by jillHuang7** [comment]
I downloaded the last version of LabD on GitHub to make sure it is a right
one, but there is an error with
private ShapeContainer shapeContainer;

Here is where I downloaded. I hope this id right place.
https://github.com/CS111C-META-FALL-2016/LabD-Team1/releases/tag/submission

**Comment by alternatebow** [comment]
Anybody getting this error? 

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: RecursionProgram$DrawingPanel
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: RecursionProgram$DrawingPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by karlnicholas** [comment]
I was playing with the repo soybe I licked something up. I'll have a look tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by karlnicholas** [comment]
No guys, everything looks good from here. delete all your .class files and re-compile all the .java files and it should work fine. Let me know.

**Comment by karlnicholas** [comment]
Hey Jill, were you able to compile the application and follow the instructions?

**Comment by karlnicholas** [comment]
[How to make an executable jar file ...](http://stackoverflow.com/questions/5258159/how-to-make-an-executable-jar-file)

**Comment by alternatebow** [comment]
I think I was able to create one but I'm only able to execute it from the
command prompt

**Comment by karlnicholas** [comment]
You need to associate a .jar file with java.
