### ISSUE TITLE
Adding a changing color option

### ISSUE THREAD

**Issue by alternatebow** [CS111C-META-FALL-2016/LabD-Team1#6]
So I'm working on a feature that uses a checkbox. The checkbox when selected will change the color of the polygons every 2 seconds or so. But the issue I'm having right now is that for some reason the method getState() is not being recognized. Any ideas? 

// colorChange is a instance of JCheckBox

else if(e.getSource().equals(colorChange)){
			shapeContainer.setColorChange(!(colorChange.getState()));
		}

**Comment by karlnicholas** [comment]
We're using Swing, not AWT, so you want a JCheckBox, not a CheckBox. That uses isSelected(). 

http://stackoverflow.com/questions/3599908/how-to-check-that-a-jcheckbox-is-checked

https://docs.oracle.com/javase/7/docs/api/javax/swing/JCheckBox.html

**Comment by jillHuang7** [comment]
I am wondering if you guys can run the program? Mine is no error just warning, but when I try to run it, there is nothing appear on the screen.

**Comment by karlnicholas** [comment]
Make sure you have the latest version pull from github. Do a clean rebuild. Run RecurseProgram. Should work.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Mon, Oct 3, 2016 at 6:35 PM -0700, "jillHuang7" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am wondering if you guys can run the program? Mine is no error just warning, but when I try to run it, there is nothing appear on the screen.

-

**Comment by alternatebow** [comment]
What he said.

**Comment by jillHuang7** [comment]
Yes! It works now!! Oh my.. astonishing!
