### ISSUE TITLE
Upper Tools/Buttons panel

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabD-Team1#7]
Let's make a JPanel  for the Border.NORTH and put the animate button (and your new checkbox maybe) on it because the number of buttons on the bottom is increasing the width to greater than 500 pixels. I'd like to keep the drawingPanel at 500x500 so that it looks good.

**Comment by alternatebow** [comment]
Yeah sounds good to me.

**Comment by karlnicholas** [comment]
You want to handle it? I just added a new Shape, but I'm going to wait on your changes before merging.

**Comment by alternatebow** [comment]
Um.. I'm still trying to figure where in the recursive call to make the
color changes.

**Comment by karlnicholas** [comment]
No hurries, I'm just screwing around. Back to other homework.

I'd suggest possibly looking at the radius value, since the recursion continues until the radius becomes less than 10. You could try to work in a recursion "counter", shouldn't be too hard. Another thought is to compute the distance from the center of the drawingPanel, which is at (250,250), though that could get a little expensive computationally.  I thought you just wanted to change the color every 2 seconds though? Anyway, knock yourself out, I'll be interested to see what you come up with.

**Comment by alternatebow** [comment]
Well that was my original thought. I have a general idea on how the whole
program works, although I'm still trying to work out the difference between
the GraphicsPolygon class and ShapeContainer class. To clarify,
RecursionProgram is where everything starts, then shapeContainer is the
'blueprint' for the polygon, whereas the GraphicsPolygon class and
RecursePolygon class are what actually displays the shapes. Is that more or
less correct?

**Comment by karlnicholas** [comment]
Yup, that's pretty much correct. I'd consider ShapeContainer really just something to hold the parameters of the program, as set by RecursionProgram. It also holds the "baseShape" or basePolygon, which is an instance of GraphicsPolygon. GraphicsPolygon is responsible for drawing itself when paintComponent is called. A GraphicsPolygon will draw itself, then it will pass the call on to all of the "Children" GraphicsPolygons on each vertix. The children polygons will also pass the call on to thier children. 

This structure of polgygons is created by RecursePolygon. When RecursePolygon is given a polygon, it will get all of the verticies and use them as center points for creating new polygons at those coordinates with a reduced radius. After it creates a new polygon at a vertix, it also calls itself (recursePolygon) for that new polygon, thus recursing until the radius becomes less than 10.

This structure is created only once for any given setting. In other words, for example, when sides is changed to 5, then ShapeContainer.rebuild() is called and the current set of polygons is wiped out and replaced with a new set. 

The animation is done with a thread that changes the radius, sides and rotation 20 times a second and calls ShapeContainer.rebuild(), then JFrame.repaint(). I was suprised you were going to mess with a thread since we haven't been taught that yet. 

I like the idea of changing the color based on the radius size. That would look cool.

**Comment by karlnicholas** [comment]
*I like the idea of changing the color based on the radius size. That would look cool.* and also wouldn't require messing with Threads.

**Comment by alternatebow** [comment]
Hmm... If I were to do this based off the radius it would also be
independent of any timer-based events too.

**Comment by karlnicholas** [comment]
Very much so, a simple change but effective because it looks cool. 

If I were to change based on time I would put a counter in the animate function and just count how many 1/20th of a seconds have passed. Every time 40 of them goes by then you could change the color. 

Kudu's if you can figure out how to add both :8ball:

**Comment by alternatebow** [comment]
Eh.... I'll try my best.

**Comment by karlnicholas** [comment]
No worries. You could also put a counter in the Animate.run() method since it has access to the shapeContainer as well.

**Comment by jillHuang7** [comment]
argh.... I had tried... kinda challenging...
I will still try.

**Comment by karlnicholas** [comment]
I went ahead and did this because I added a new shape and wanted to push this code so that you could see the changes. These changes will likely conflict with any work you have been done, so you can either 1) attempt to merge them, or 2) copy them aside, pull and overwrite everything, and reapply them. I suggest the later because it probably wouldn't be the effort to merge. From what I can tell the changes you might have made shouldn't be too hard to reapply.

For additions I suggest 1) adding new shapes. It should be a lot easier now that there are two already in there. 2) I'm still interested in the color ideas, especially if it happens during animation b/c that would look totally cool. 

Also, during animation I wanted to change the radius and rotation to go to 180 instead of 150 b/c 180 is a half circle. That can be done anytime.

Let me know what you are thinking and doing be sure to communicate so that you aren't working on the same thing as someone else.
