### ISSUE TITLE
JavaDocs

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabD-Team1#9]
Let's start commenting this code.

**Comment by jillHuang7** [comment]
I am starting commenting now.

**Comment by karlnicholas** [comment]
Hi. Put some more comments in the GraphicsBaseclass  please, especially on the recurseShape method, since that is the basis of this project. 
Put comments in the RecurseProgram since it has none.

Also, please do your pull requests all at once. There is no need to do them for each file, it just makes extra work and it's a pain. 

Also, Calvin and Lee please comment in the issues instead of the pull requests. The pull requests are temporary and not a good place for comments.

Also, everyone please add @author comments to all of the classes.

Finally, the GraphicsShape interface is commented very nicely. I don't see any need to do them all that way, but ultimately that would be the goal of comments in any project. However, there are Javadoc errors: See if you can fix them. Thanks.

C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:53: error: @param name not found
	    @param g 
	           ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:55: warning: no @param for p
	public void setVertixShape(int i, GraphicShape p);
	            ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:58: warning: no description for @param
	    @param color	@return color.
	    ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:60: warning: no description for @param
	    @param radius	@return the radius of the new shape
	    ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:61: warning: no description for @param
	    @param rotation	@return the rotation of the new shape
	    ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:62: warning: no description for @param
	    @param recursionFactor	@return the recursionFactor of the new shape*/
	    ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:63: warning: no @param for change
	public GraphicShape newShape(boolean change,Color color, int sides, Point center, int radius, double rotation, double recursionFactor, int counter);
	                    ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:63: warning: no @param for center
	public GraphicShape newShape(boolean change,Color color, int sides, Point center, int radius, double rotation, double recursionFactor, int counter);
	                    ^
C:\Users\quix0\workspace\LabD-Team1\src\GraphicShape.java:63: warning: no @param for counter
	public GraphicShape newShape(boolean change,Color color, int sides, Point center, int radius, double rotation, double recursionFactor, int counter);
	                    ^

**Comment by jillHuang7** [comment]
Hi Karl,
Thank you for checking! 
Please check if there is still some error  in the GraphicsShape interface.
I have one issue with the update. It shows:
Please make sure you have the correct access rights
and the repository exists.

Is it means I need a permission?

**Comment by karlnicholas** [comment]
Hi Jill, 
I was playing around with the organization and repo permissions yesterday so I'm not surprised. I see the changes you push to master, so there must be a merge conflict. 

You can do a fresh pull and reapply your changes or you can make your changes on a new branch.

Then you will either need to push the new branch and make a pull request and I'll do the merge, or merge the new branch changes into the master branch.  First, be sure to update your master branch first. It sounds like its out of date. That might require a "rebase" or "reset" with overwrite to delete the out of sync changes you already made.

If it gets too complicated delete the project and fetch it again new and reapply your changes.

**Comment by karlnicholas** [comment]
Javadocs looks pretty good?

**Comment by karlnicholas** [comment]
Outstanding.
